version: "3.9"
services:
  back-dev:
    depends_on:
      - mongo-dev
    networks:
      - tp-docker-network
    container_name: back-dev
    image: back:dev
    build:
      context: server/
      target: dev
      dockerfile: Dockerfile
    volumes:
      - ./server:/develop
    environment:
      - MONGODB=${MONGODB}
    ports:
      - 3000:3000
    tty: true

  front-dev:
    networks:
      - tp-docker-network
    container_name: front-dev
    image: front:dev
    build:
      context: client/
      target: dev
      dockerfile: Dockerfile
    volumes:
      - ./client:/develop
    ports:
      - 5173:5173
    tty: true

  mongo-dev:
    networks:
      - tp-docker-network
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    ports:
      - "27017:27017"
    volumes:
      - mongo-dev-data:/data/db

volumes:
  mongo-dev-data:

networks:
  tp-docker-network:
