version: "3.9"
services:
  back-dev:
    depends_on:
      - mongo
    networks:
      - tp-docker-back # Connecte ce service au réseau "tp-docker-back"
      - tp-docker-code # Connecte ce service au réseau "tp-docker-code".
    container_name: back-dev
    image: back:dev
    build:
      context: server/
      target: dev
      dockerfile: Dockerfile
    volumes:
      - ./server:/develop # Volume partagé répertoire local dans le conteneur
    environment:
      - SALT=${SALT} # Configuration des variables d'environnement.
      - JWT=${JWT}
    ports:
      - 3000:3000 # Mappage du port hôte/conteneur.
    tty: true # Alloue un terminal TTY pour ce service.

  front-dev:
    networks:
      - tp-docker-code
    container_name: front-dev
    image: front:dev
    build:
      context: client/
      target: dev
      dockerfile: Dockerfile
    volumes:
      - ./client:/develop # Volume partagé répertoire local dans le conteneur
    ports:
      - 5173:5173
    tty: true # Alloue un terminal TTY pour ce service.

  mongo:
    networks:
      - tp-docker-back
    image: mongodb/mongodb-community-server:7.0.0-ubi8
    ports:
      - "27017:27017" # Mappage du port hôte/conteneur.
    volumes:
      - mongo-dev-data:/data/db # Volume persistante pour les données de MongoDB.

# Définition du volume pour les données MongoDB.
volumes:
  mongo-dev-data:

# Définition du réseaux
networks:
  tp-docker-code: 
  tp-docker-back:
